// <auto-generated />
namespace HellDay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addednametoRegisterBindingModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednametoRegisterBindingModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031749400_addednametoRegisterBindingModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
